# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ice_beam.root] run return 0
function #animated_java:ice_beam/as_root/pre_tick
execute if entity @s[tag=aj.ice_beam.animation.default.playing] run function animated_java:ice_beam/animations/default/zzz/on_tick
execute on passengers if entity @s[tag=aj.ice_beam.data] run function animated_java:ice_beam/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
function #animated_java:ice_beam/as_root/post_tick