# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.muscleroom.root] run return 0
function #animated_java:muscleroom/as_root/pre_tick
execute if entity @s[tag=aj.muscleroom.animation.default.playing] run function animated_java:muscleroom/animations/default/zzz/on_tick
execute if entity @s[tag=aj.muscleroom.animation.walk.playing] run function animated_java:muscleroom/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.muscleroom.animation.jump.playing] run function animated_java:muscleroom/animations/jump/zzz/on_tick
execute if entity @s[tag=aj.muscleroom.animation.ground.playing] run function animated_java:muscleroom/animations/ground/zzz/on_tick
execute if entity @s[tag=aj.muscleroom.animation.bark.playing] run function animated_java:muscleroom/animations/bark/zzz/on_tick
execute if entity @s[tag=aj.muscleroom.animation.die.playing] run function animated_java:muscleroom/animations/die/zzz/on_tick
execute if entity @s[tag=aj.muscleroom.animation.left_punch.playing] run function animated_java:muscleroom/animations/left_punch/zzz/on_tick
execute if entity @s[tag=aj.muscleroom.animation.ground1.playing] run function animated_java:muscleroom/animations/ground1/zzz/on_tick
execute if entity @s[tag=aj.muscleroom.animation.ground2.playing] run function animated_java:muscleroom/animations/ground2/zzz/on_tick
execute if entity @s[tag=aj.muscleroom.animation.backstep.playing] run function animated_java:muscleroom/animations/backstep/zzz/on_tick
execute if entity @s[tag=aj.muscleroom.animation.left_punch1.playing] run function animated_java:muscleroom/animations/left_punch1/zzz/on_tick
execute if entity @s[tag=aj.muscleroom.animation.left_punch2.playing] run function animated_java:muscleroom/animations/left_punch2/zzz/on_tick
execute if entity @s[tag=aj.muscleroom.animation.tired.playing] run function animated_java:muscleroom/animations/tired/zzz/on_tick
execute on passengers if entity @s[tag=aj.muscleroom.data] run function animated_java:muscleroom/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
execute on vehicle run function anemoland_contents:sys/entity/mob/muscleroom/tick/0
function #animated_java:muscleroom/as_root/post_tick