# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:human1/animations/keep_distance_copy2/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.keep_distance_copy2.frame 1