# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.hitbox_tail1
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.hitbox_tail2
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.hitbox_tail3
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.hitbox_body2
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.hitbox_body3
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.hitbox_neck1
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.hitbox_neck2
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.hitbox_head