# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.garuda.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'garuda', 'function_path': 'animated_java:garuda/animations/pause_all'}
tag @s remove aj.garuda.animation.default.playing
tag @s remove aj.garuda.animation.die.playing
tag @s remove aj.garuda.animation.walk.playing
tag @s remove aj.garuda.animation.bark.playing
tag @s remove aj.garuda.animation.pick1_jump.playing
tag @s remove aj.garuda.animation.pick2.playing
tag @s remove aj.garuda.animation.wing_left1.playing
tag @s remove aj.garuda.animation.wing_left2.playing
tag @s remove aj.garuda.animation.pick1.playing
tag @s remove aj.garuda.animation.jump1.playing
tag @s remove aj.garuda.animation.jump2.playing
tag @s remove aj.garuda.animation.jump3.playing
tag @s remove aj.garuda.animation.tired.playing
tag @s remove aj.garuda.animation.dash1.playing
tag @s remove aj.garuda.animation.dash2.playing
tag @s remove aj.garuda.animation.dash3.playing
tag @s remove aj.garuda.animation.fly_keep.playing
tag @s remove aj.garuda.animation.summer_salt_right1.playing
tag @s remove aj.garuda.animation.summer_salt_right2.playing
tag @s remove aj.garuda.animation.summer_salt_right1_copy.playing