# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:martellos/root/zzz/1 with entity @s data.locators.hitbox_head
function animated_java:martellos/root/zzz/3 with entity @s data.locators.hitbox_neck
function animated_java:martellos/root/zzz/5 with entity @s data.locators.hitbox_right_arm
function animated_java:martellos/root/zzz/7 with entity @s data.locators.hitbox_left_arm
function animated_java:martellos/root/zzz/9 with entity @s data.locators.hitbox_tail1
function animated_java:martellos/root/zzz/11 with entity @s data.locators.hitbox_tail2