# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:garapapas/remove/zzz/kill with entity @s data.locators.hitbox_right_leg
function animated_java:garapapas/remove/zzz/kill with entity @s data.locators.hitbox_left_leg
function animated_java:garapapas/remove/zzz/kill with entity @s data.locators.hitbox_tail2
function animated_java:garapapas/remove/zzz/kill with entity @s data.locators.hitbox_tail1
function animated_java:garapapas/remove/zzz/kill with entity @s data.locators.hitbox_neck
function animated_java:garapapas/remove/zzz/kill with entity @s data.locators.head
function animated_java:garapapas/remove/zzz/kill with entity @s data.locators.hitbox_front_body
function animated_java:garapapas/remove/zzz/kill with entity @s data.locators.hitbox_right_arm
function animated_java:garapapas/remove/zzz/kill with entity @s data.locators.hitbox_left_arm