# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.decoy1.root] run return 0
function #animated_java:decoy1/as_root/pre_tick
execute if entity @s[tag=aj.decoy1.animation.default.playing] run function animated_java:decoy1/animations/default/zzz/on_tick
execute if entity @s[tag=aj.decoy1.animation.die.playing] run function animated_java:decoy1/animations/die/zzz/on_tick
execute on passengers if entity @s[tag=aj.decoy1.data] run function animated_java:decoy1/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
execute on vehicle run function anemoland_contents:sys/entity/mob/decoy1/tick/0
function #animated_java:decoy1/as_root/post_tick