# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle poof ~ ~-1 ~ 2 0 2 0 20
execute as @a[distance=..64] at @s run playsound entity.generic.explode hostile @s ~ ~ ~ 1 0