# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute rotated ~ 0 run particle flame ^ ^1 ^-1 0.1 0.1 0.1 0.1 10
execute rotated ~ 0 positioned ^ ^ ^-3 as @e[type=armor_stand,tag=bullet.ignitable_dust,tag=!ignited,distance=..12] run function rpg:sys/entity/bullet/ignitable_dust/fire