# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:ojinushi/remove/zzz/kill with entity @s data.locators.right_arm
function animated_java:ojinushi/remove/zzz/kill with entity @s data.locators.head
function animated_java:ojinushi/remove/zzz/kill with entity @s data.locators.left_arm