# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:human1/animations/thinking/zzz/apply_frame {frame: 80}
scoreboard players add @s aj.thinking.frame 1