# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_tail1.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_tail2.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_tail3.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_body2.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_body3.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_neck1.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_neck2.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_head.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator.uuid
function animated_java:carnara/zzz/execute with storage aj:temp