# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.muscleroom.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'muscleroom', 'function_path': 'animated_java:muscleroom/animations/left_punch1/next_frame'}
execute if score @s aj.left_punch1.frame matches 41.. run scoreboard players set @s aj.left_punch1.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.left_punch1.frame
execute at @s run function animated_java:muscleroom/animations/left_punch1/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.left_punch1.frame 1