# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.squirrel_head.root] run return 0
function #animated_java:squirrel_head/as_root/pre_tick
execute if entity @s[tag=aj.squirrel_head.animation.default.playing] run function animated_java:squirrel_head/animations/default/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.die.playing] run function animated_java:squirrel_head/animations/die/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.bite1.playing] run function animated_java:squirrel_head/animations/bite1/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.bite2.playing] run function animated_java:squirrel_head/animations/bite2/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.spin_left1.playing] run function animated_java:squirrel_head/animations/spin_left1/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.spin_left2.playing] run function animated_java:squirrel_head/animations/spin_left2/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.spin_right1.playing] run function animated_java:squirrel_head/animations/spin_right1/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.spin_right2.playing] run function animated_java:squirrel_head/animations/spin_right2/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.walk.playing] run function animated_java:squirrel_head/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.bite_left1.playing] run function animated_java:squirrel_head/animations/bite_left1/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.bite_left2.playing] run function animated_java:squirrel_head/animations/bite_left2/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.bite_right1.playing] run function animated_java:squirrel_head/animations/bite_right1/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.bite_right2.playing] run function animated_java:squirrel_head/animations/bite_right2/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.tackle_left1.playing] run function animated_java:squirrel_head/animations/tackle_left1/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.tackle_left2.playing] run function animated_java:squirrel_head/animations/tackle_left2/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.tackle_right1.playing] run function animated_java:squirrel_head/animations/tackle_right1/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.tackle_right2.playing] run function animated_java:squirrel_head/animations/tackle_right2/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.bark.playing] run function animated_java:squirrel_head/animations/bark/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.tired.playing] run function animated_java:squirrel_head/animations/tired/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.spin_tail_left1.playing] run function animated_java:squirrel_head/animations/spin_tail_left1/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.spin_jump_left1.playing] run function animated_java:squirrel_head/animations/spin_jump_left1/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.spin_jump_left2.playing] run function animated_java:squirrel_head/animations/spin_jump_left2/zzz/on_tick
execute if entity @s[tag=aj.squirrel_head.animation.spin_jump3.playing] run function animated_java:squirrel_head/animations/spin_jump3/zzz/on_tick
execute on passengers if entity @s[tag=aj.squirrel_head.data] run function animated_java:squirrel_head/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
execute on vehicle run function anemoland_contents:sys/entity/mob/squirrel_head/tick/0
function #animated_java:squirrel_head/as_root/post_tick