# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.garapapas.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'garapapas', 'function_path': 'animated_java:garapapas/animations/pause_all'}
tag @s remove aj.garapapas.animation.default.playing
tag @s remove aj.garapapas.animation.die.playing
tag @s remove aj.garapapas.animation.bite1.playing
tag @s remove aj.garapapas.animation.bite2.playing
tag @s remove aj.garapapas.animation.bark.playing
tag @s remove aj.garapapas.animation.dive1.playing
tag @s remove aj.garapapas.animation.dive2.playing
tag @s remove aj.garapapas.animation.tired.playing
tag @s remove aj.garapapas.animation.walk.playing
tag @s remove aj.garapapas.animation.bite_left1.playing
tag @s remove aj.garapapas.animation.bite_left2.playing
tag @s remove aj.garapapas.animation.tail_left1.playing
tag @s remove aj.garapapas.animation.tail_left2.playing
tag @s remove aj.garapapas.animation.water_front1.playing
tag @s remove aj.garapapas.animation.water_front2.playing
tag @s remove aj.garapapas.animation.bite_right1.playing
tag @s remove aj.garapapas.animation.bite_right2.playing
tag @s remove aj.garapapas.animation.tail_right1.playing
tag @s remove aj.garapapas.animation.tail_right2.playing