# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.walking_mushroom.root] run return 0
function #animated_java:walking_mushroom/as_root/pre_tick
execute if entity @s[tag=aj.walking_mushroom.animation.default.playing] run function animated_java:walking_mushroom/animations/default/zzz/on_tick
execute if entity @s[tag=aj.walking_mushroom.animation.walk.playing] run function animated_java:walking_mushroom/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.walking_mushroom.animation.die.playing] run function animated_java:walking_mushroom/animations/die/zzz/on_tick
execute if entity @s[tag=aj.walking_mushroom.animation.attack.playing] run function animated_java:walking_mushroom/animations/attack/zzz/on_tick
execute on passengers if entity @s[tag=aj.walking_mushroom.data] run function animated_java:walking_mushroom/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
function anemoland_contents:sys/entity/mob/walking_mushroom/tick/0
function #animated_java:walking_mushroom/as_root/post_tick