# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.squirrel_head.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'squirrel_head', 'function_path': 'animated_java:squirrel_head/variants/default/apply'}
execute on passengers if entity @s[tag=aj.squirrel_head.bone.right_leg] run function animated_java:squirrel_head/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.squirrel_head.bone.left_leg] run function animated_java:squirrel_head/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.squirrel_head.bone.tail] run function animated_java:squirrel_head/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.squirrel_head.bone.jaw] run function animated_java:squirrel_head/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.squirrel_head.bone.head] run function animated_java:squirrel_head/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.squirrel_head.bone.neck2] run function animated_java:squirrel_head/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.squirrel_head.bone.neck1] run function animated_java:squirrel_head/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.squirrel_head.bone.front_body] run function animated_java:squirrel_head/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.squirrel_head.bone.back_body] run function animated_java:squirrel_head/variants/default/zzz/8