# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.garapapas.root] run return 0
function #animated_java:garapapas/as_root/pre_tick
execute if entity @s[tag=aj.garapapas.animation.default.playing] run function animated_java:garapapas/animations/default/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.die.playing] run function animated_java:garapapas/animations/die/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.bite1.playing] run function animated_java:garapapas/animations/bite1/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.bite2.playing] run function animated_java:garapapas/animations/bite2/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.bark.playing] run function animated_java:garapapas/animations/bark/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.dive1.playing] run function animated_java:garapapas/animations/dive1/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.dive2.playing] run function animated_java:garapapas/animations/dive2/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.tired.playing] run function animated_java:garapapas/animations/tired/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.walk.playing] run function animated_java:garapapas/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.bite_left1.playing] run function animated_java:garapapas/animations/bite_left1/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.bite_left2.playing] run function animated_java:garapapas/animations/bite_left2/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.tail_left1.playing] run function animated_java:garapapas/animations/tail_left1/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.tail_left2.playing] run function animated_java:garapapas/animations/tail_left2/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.water_front1.playing] run function animated_java:garapapas/animations/water_front1/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.water_front2.playing] run function animated_java:garapapas/animations/water_front2/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.bite_right1.playing] run function animated_java:garapapas/animations/bite_right1/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.bite_right2.playing] run function animated_java:garapapas/animations/bite_right2/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.tail_right1.playing] run function animated_java:garapapas/animations/tail_right1/zzz/on_tick
execute if entity @s[tag=aj.garapapas.animation.tail_right2.playing] run function animated_java:garapapas/animations/tail_right2/zzz/on_tick
execute on passengers if entity @s[tag=aj.garapapas.data] run function animated_java:garapapas/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
execute on vehicle run function anemoland_contents:sys/entity/mob/garapapas/tick/0
function #animated_java:garapapas/as_root/post_tick