# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.ojinushi.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ojinushi', 'function_path': 'animated_java:ojinushi/animations/pause_all'}
tag @s remove aj.ojinushi.animation.default.playing
tag @s remove aj.ojinushi.animation.die.playing
tag @s remove aj.ojinushi.animation.right_punch.playing
tag @s remove aj.ojinushi.animation.launch.playing
tag @s remove aj.ojinushi.animation.bark.playing
tag @s remove aj.ojinushi.animation.jump_launch1.playing
tag @s remove aj.ojinushi.animation.jump_launch2.playing
tag @s remove aj.ojinushi.animation.jump_launch2_right2.playing
tag @s remove aj.ojinushi.animation.jump_launch2_right.playing
tag @s remove aj.ojinushi.animation.bite.playing
tag @s remove aj.ojinushi.animation.bite_left.playing
tag @s remove aj.ojinushi.animation.bite_right.playing
tag @s remove aj.ojinushi.animation.walk.playing
tag @s remove aj.ojinushi.animation.tired.playing
tag @s remove aj.ojinushi.animation.right_punch1.playing
tag @s remove aj.ojinushi.animation.right_punch2.playing
tag @s remove aj.ojinushi.animation.bite_right1.playing
tag @s remove aj.ojinushi.animation.bite_right2.playing
tag @s remove aj.ojinushi.animation.bite_left1.playing
tag @s remove aj.ojinushi.animation.bite_left2.playing
tag @s remove aj.ojinushi.animation.launch1.playing
tag @s remove aj.ojinushi.animation.launch2.playing
tag @s remove aj.ojinushi.animation.sidestep_left.playing
tag @s remove aj.ojinushi.animation.launch_up.playing
tag @s remove aj.ojinushi.animation.sidestep_right.playing