# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.raptor.root] run return 0
function #animated_java:raptor/as_root/pre_tick
execute if entity @s[tag=aj.raptor.animation.default.playing] run function animated_java:raptor/animations/default/zzz/on_tick
execute if entity @s[tag=aj.raptor.animation.die.playing] run function animated_java:raptor/animations/die/zzz/on_tick
execute if entity @s[tag=aj.raptor.animation.walk.playing] run function animated_java:raptor/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.raptor.animation.jump_charge.playing] run function animated_java:raptor/animations/jump_charge/zzz/on_tick
execute if entity @s[tag=aj.raptor.animation.jump.playing] run function animated_java:raptor/animations/jump/zzz/on_tick
execute if entity @s[tag=aj.raptor.animation.jump_end.playing] run function animated_java:raptor/animations/jump_end/zzz/on_tick
execute if entity @s[tag=aj.raptor.animation.left_jump.playing] run function animated_java:raptor/animations/left_jump/zzz/on_tick
execute if entity @s[tag=aj.raptor.animation.bark.playing] run function animated_java:raptor/animations/bark/zzz/on_tick
execute if entity @s[tag=aj.raptor.animation.right_jump.playing] run function animated_java:raptor/animations/right_jump/zzz/on_tick
execute on passengers if entity @s[tag=aj.raptor.data] run function animated_java:raptor/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
execute on vehicle run function anemoland_contents:sys/entity/mob/raptor/tick/0
function #animated_java:raptor/as_root/post_tick