# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:garuda/root/zzz/1 with entity @s data.locators.hitbox_right_wing1
function animated_java:garuda/root/zzz/3 with entity @s data.locators.hitbox_right_wing2
function animated_java:garuda/root/zzz/5 with entity @s data.locators.hitbox_right_wing3
function animated_java:garuda/root/zzz/7 with entity @s data.locators.hitbox_left_wing1
function animated_java:garuda/root/zzz/9 with entity @s data.locators.hitbox_left_wing2
function animated_java:garuda/root/zzz/11 with entity @s data.locators.hitbox_left_wing3
function animated_java:garuda/root/zzz/13 with entity @s data.locators.neck
function animated_java:garuda/root/zzz/15 with entity @s data.locators.hitbox_head
function animated_java:garuda/root/zzz/17 with entity @s data.locators.hitbox_tail1
function animated_java:garuda/root/zzz/19 with entity @s data.locators.hitbox_tail2