# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.walking_mushroom.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'walking_mushroom', 'function_path': 'animated_java:walking_mushroom/animations/pause_all'}
tag @s remove aj.walking_mushroom.animation.default.playing
tag @s remove aj.walking_mushroom.animation.walk.playing
tag @s remove aj.walking_mushroom.animation.die.playing
tag @s remove aj.walking_mushroom.animation.attack.playing