# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:carnara/root/zzz/1 with entity @s data.locators.tail1
function animated_java:carnara/root/zzz/3 with entity @s data.locators.tail2
function animated_java:carnara/root/zzz/5 with entity @s data.locators.tail3
function animated_java:carnara/root/zzz/7 with entity @s data.locators.body2
function animated_java:carnara/root/zzz/9 with entity @s data.locators.body3
function animated_java:carnara/root/zzz/11 with entity @s data.locators.neck1
function animated_java:carnara/root/zzz/13 with entity @s data.locators.neck2
function animated_java:carnara/root/zzz/15 with entity @s data.locators.head