# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:bagikeros/animations/tired/zzz/apply_frame {frame: 80}
scoreboard players add @s aj.tired.frame 1