# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.garuda.locator', 'aj.garuda.locator.hitbox_right_wing1']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:garuda/zzz/2
data modify entity @s data.locators.hitbox_right_wing1.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.garuda.locator', 'aj.garuda.locator.hitbox_right_wing2']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:garuda/zzz/3
data modify entity @s data.locators.hitbox_right_wing2.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.garuda.locator', 'aj.garuda.locator.hitbox_right_wing3']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:garuda/zzz/4
data modify entity @s data.locators.hitbox_right_wing3.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.garuda.locator', 'aj.garuda.locator.hitbox_left_wing1']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:garuda/zzz/5
data modify entity @s data.locators.hitbox_left_wing1.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.garuda.locator', 'aj.garuda.locator.hitbox_left_wing2']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:garuda/zzz/6
data modify entity @s data.locators.hitbox_left_wing2.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.garuda.locator', 'aj.garuda.locator.hitbox_left_wing3']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:garuda/zzz/7
data modify entity @s data.locators.hitbox_left_wing3.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.garuda.locator', 'aj.garuda.locator.neck']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:garuda/zzz/8
data modify entity @s data.locators.neck.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.garuda.locator', 'aj.garuda.locator.hitbox_head']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:garuda/zzz/9
data modify entity @s data.locators.hitbox_head.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.garuda.locator', 'aj.garuda.locator.hitbox_tail1']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:garuda/zzz/10
data modify entity @s data.locators.hitbox_tail1.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.garuda.locator', 'aj.garuda.locator.hitbox_tail2']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:garuda/zzz/11
data modify entity @s data.locators.hitbox_tail2.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_leg4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_leg3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_leg1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_leg4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_leg3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_leg1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_wing3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_wing3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_wing2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_wing2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_wing1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_wing1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_wing3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_wing3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_wing2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_wing2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_wing1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_wing1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.beak_down] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_beak_down set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.beak_up] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_beak_up set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.head1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.neck2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.neck1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.body3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.body2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.tail2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.tail1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.body1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body1 set from storage aj:uuid main.out