# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_right_wing1.uuid
function animated_java:garuda/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_right_wing2.uuid
function animated_java:garuda/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_right_wing3.uuid
function animated_java:garuda/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_left_wing1.uuid
function animated_java:garuda/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_left_wing2.uuid
function animated_java:garuda/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_left_wing3.uuid
function animated_java:garuda/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.neck.uuid
function animated_java:garuda/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_head.uuid
function animated_java:garuda/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_tail1.uuid
function animated_java:garuda/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_tail2.uuid
function animated_java:garuda/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator.uuid
function animated_java:garuda/zzz/execute with storage aj:temp