# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.bagikeros.root] run return 0
function #animated_java:bagikeros/as_root/pre_tick
execute if entity @s[tag=aj.bagikeros.animation.default.playing] run function animated_java:bagikeros/animations/default/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.die.playing] run function animated_java:bagikeros/animations/die/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.bite1.playing] run function animated_java:bagikeros/animations/bite1/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.bite2.playing] run function animated_java:bagikeros/animations/bite2/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.bark.playing] run function animated_java:bagikeros/animations/bark/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.dive1.playing] run function animated_java:bagikeros/animations/dive1/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.dive2.playing] run function animated_java:bagikeros/animations/dive2/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.shake_head1.playing] run function animated_java:bagikeros/animations/shake_head1/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.shake_head2.playing] run function animated_java:bagikeros/animations/shake_head2/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.walk.playing] run function animated_java:bagikeros/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.shake_walk.playing] run function animated_java:bagikeros/animations/shake_walk/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.shake_tail1.playing] run function animated_java:bagikeros/animations/shake_tail1/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.shake_tail2.playing] run function animated_java:bagikeros/animations/shake_tail2/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.shake_walk_end.playing] run function animated_java:bagikeros/animations/shake_walk_end/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.shake_walk_start.playing] run function animated_java:bagikeros/animations/shake_walk_start/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.bite_left1.playing] run function animated_java:bagikeros/animations/bite_left1/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.bite_left2.playing] run function animated_java:bagikeros/animations/bite_left2/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.bite_right1.playing] run function animated_java:bagikeros/animations/bite_right1/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.bite_right2.playing] run function animated_java:bagikeros/animations/bite_right2/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.tired.playing] run function animated_java:bagikeros/animations/tired/zzz/on_tick
execute if entity @s[tag=aj.bagikeros.animation.fire_head.playing] run function animated_java:bagikeros/animations/fire_head/zzz/on_tick
execute on passengers if entity @s[tag=aj.bagikeros.data] run function animated_java:bagikeros/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
execute on vehicle run function anemoland_contents:sys/entity/mob/bagikeros/tick/0
function #animated_java:bagikeros/as_root/post_tick