# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.garapapas.locator', 'aj.garapapas.locator.right_leg']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:garapapas/zzz/2
data modify entity @s data.locators.right_leg.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.garapapas.locator', 'aj.garapapas.locator.left_leg']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:garapapas/zzz/3
data modify entity @s data.locators.left_leg.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.garapapas.locator', 'aj.garapapas.locator.tail2']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:garapapas/zzz/4
data modify entity @s data.locators.tail2.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.garapapas.locator', 'aj.garapapas.locator.tail1']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:garapapas/zzz/5
data modify entity @s data.locators.tail1.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.garapapas.locator', 'aj.garapapas.locator.neck']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:garapapas/zzz/6
data modify entity @s data.locators.neck.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.garapapas.locator', 'aj.garapapas.locator.head']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:garapapas/zzz/7
data modify entity @s data.locators.head.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.garapapas.locator', 'aj.garapapas.locator.front_body']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:garapapas/zzz/8
data modify entity @s data.locators.front_body.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.garapapas.locator', 'aj.garapapas.locator.right_arm']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:garapapas/zzz/9
data modify entity @s data.locators.right_arm.uuid set from storage aj:uuid main.out
summon minecraft:pig ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.garapapas.locator', 'aj.garapapas.locator.left_arm']}
execute as @e[type=minecraft:pig,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:garapapas/zzz/10
data modify entity @s data.locators.left_arm.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.right_leg3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.right_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.right_leg1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.left_leg3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.left_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.left_leg1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.tail2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.tail1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.beak_up] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_beak_up set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.beak_down] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_beak_down set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.neck2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.neck1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.right_arm3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.right_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.right_arm1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.left_arm3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.left_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.left_arm1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.front_body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_front_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garapapas.bone.back_body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_back_body set from storage aj:uuid main.out