# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:boar/animations/large_walk/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.large_walk.frame 1