# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:spider/animations/default/zzz/apply_frame {frame: 2}
scoreboard players add @s aj.default.frame 1