# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:garapas/animations/walk/zzz/apply_frame {frame: 28}
scoreboard players add @s aj.walk.frame 1