# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.spider.root] run return 0
function #animated_java:spider/as_root/pre_tick
execute if entity @s[tag=aj.spider.animation.default.playing] run function animated_java:spider/animations/default/zzz/on_tick
execute if entity @s[tag=aj.spider.animation.die.playing] run function animated_java:spider/animations/die/zzz/on_tick
execute if entity @s[tag=aj.spider.animation.walk.playing] run function animated_java:spider/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.spider.animation.jump_charge.playing] run function animated_java:spider/animations/jump_charge/zzz/on_tick
execute if entity @s[tag=aj.spider.animation.jump.playing] run function animated_java:spider/animations/jump/zzz/on_tick
execute if entity @s[tag=aj.spider.animation.jump_end.playing] run function animated_java:spider/animations/jump_end/zzz/on_tick
execute on passengers if entity @s[tag=aj.spider.data] run function animated_java:spider/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
execute on vehicle run function anemoland_contents:sys/entity/mob/spider/tick/0
function #animated_java:spider/as_root/post_tick