# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:human1/animations/keep_distance1/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.keep_distance1.frame 1