# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.garapas.root] run return 0
function #animated_java:garapas/as_root/pre_tick
execute if entity @s[tag=aj.garapas.animation.default.playing] run function animated_java:garapas/animations/default/zzz/on_tick
execute if entity @s[tag=aj.garapas.animation.die.playing] run function animated_java:garapas/animations/die/zzz/on_tick
execute if entity @s[tag=aj.garapas.animation.bite.playing] run function animated_java:garapas/animations/bite/zzz/on_tick
execute if entity @s[tag=aj.garapas.animation.walk.playing] run function animated_java:garapas/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.garapas.animation.water_front.playing] run function animated_java:garapas/animations/water_front/zzz/on_tick
execute on passengers if entity @s[tag=aj.garapas.data] run function animated_java:garapas/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
execute on vehicle run function anemoland_contents:sys/entity/mob/garapas/tick/0
function #animated_java:garapas/as_root/post_tick