# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.martellos.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'martellos', 'function_path': 'animated_java:martellos/animations/pause_all'}
tag @s remove aj.martellos.animation.default.playing
tag @s remove aj.martellos.animation.bark.playing
tag @s remove aj.martellos.animation.walk.playing
tag @s remove aj.martellos.animation.turn_right.playing
tag @s remove aj.martellos.animation.turn_left.playing
tag @s remove aj.martellos.animation.die.playing
tag @s remove aj.martellos.animation.tired.playing
tag @s remove aj.martellos.animation.dash_charge.playing
tag @s remove aj.martellos.animation.dash.playing
tag @s remove aj.martellos.animation.dash_end.playing
tag @s remove aj.martellos.animation.knock_right1.playing
tag @s remove aj.martellos.animation.knock_right2.playing
tag @s remove aj.martellos.animation.knock_left1.playing
tag @s remove aj.martellos.animation.knock_left2.playing
tag @s remove aj.martellos.animation.spin_right1.playing
tag @s remove aj.martellos.animation.spin_right2.playing
tag @s remove aj.martellos.animation.spin_dirt_right1.playing
tag @s remove aj.martellos.animation.spin_dirt_right2.playing
tag @s remove aj.martellos.animation.tail_right1.playing
tag @s remove aj.martellos.animation.backstep.playing
tag @s remove aj.martellos.animation.backstep2.playing