# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:spider/animations/jump/zzz/apply_frame {frame: 8}
scoreboard players add @s aj.jump.frame 1