# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.boar.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'boar', 'function_path': 'animated_java:boar/variants/damaged/apply'}
execute on passengers if entity @s[tag=aj.boar.bone.head] run function animated_java:boar/variants/damaged/zzz/0
execute on passengers if entity @s[tag=aj.boar.bone.back_right_leg] run function animated_java:boar/variants/damaged/zzz/1
execute on passengers if entity @s[tag=aj.boar.bone.back_left_leg] run function animated_java:boar/variants/damaged/zzz/2
execute on passengers if entity @s[tag=aj.boar.bone.front_right_leg] run function animated_java:boar/variants/damaged/zzz/3
execute on passengers if entity @s[tag=aj.boar.bone.front_left_leg] run function animated_java:boar/variants/damaged/zzz/4
execute on passengers if entity @s[tag=aj.boar.bone.body] run function animated_java:boar/variants/damaged/zzz/5