# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:garuda/remove/zzz/kill with entity @s data.locators.hitbox_right_wing1
function animated_java:garuda/remove/zzz/kill with entity @s data.locators.hitbox_right_wing2
function animated_java:garuda/remove/zzz/kill with entity @s data.locators.hitbox_right_wing3
function animated_java:garuda/remove/zzz/kill with entity @s data.locators.hitbox_left_wing1
function animated_java:garuda/remove/zzz/kill with entity @s data.locators.hitbox_left_wing2
function animated_java:garuda/remove/zzz/kill with entity @s data.locators.hitbox_left_wing3
function animated_java:garuda/remove/zzz/kill with entity @s data.locators.neck
function animated_java:garuda/remove/zzz/kill with entity @s data.locators.hitbox_head
function animated_java:garuda/remove/zzz/kill with entity @s data.locators.hitbox_tail1
function animated_java:garuda/remove/zzz/kill with entity @s data.locators.hitbox_tail2