# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.tail1.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.tail2.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.tail3.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.body2.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.body3.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.neck1.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.neck2.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.head.uuid
function animated_java:carnara/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator.uuid
function animated_java:carnara/zzz/execute with storage aj:temp