# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:squirrel_head/remove/zzz/kill with entity @s data.locators.tail
function animated_java:squirrel_head/remove/zzz/kill with entity @s data.locators.tail2
function animated_java:squirrel_head/remove/zzz/kill with entity @s data.locators.neck
function animated_java:squirrel_head/remove/zzz/kill with entity @s data.locators.head