# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.tail1
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.tail2
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.tail3
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.body2
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.body3
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.neck1
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.neck2
function animated_java:carnara/remove/zzz/kill with entity @s data.locators.head