# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.human1.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'human1', 'function_path': 'animated_java:human1/variants/sally_damaged/apply'}
execute on passengers if entity @s[tag=aj.human1.bone.head] run function animated_java:human1/variants/sally_damaged/zzz/0
execute on passengers if entity @s[tag=aj.human1.bone.left_arm2] run function animated_java:human1/variants/sally_damaged/zzz/1
execute on passengers if entity @s[tag=aj.human1.bone.left_arm] run function animated_java:human1/variants/sally_damaged/zzz/2
execute on passengers if entity @s[tag=aj.human1.bone.right_arm2] run function animated_java:human1/variants/sally_damaged/zzz/3
execute on passengers if entity @s[tag=aj.human1.bone.right_arm] run function animated_java:human1/variants/sally_damaged/zzz/4
execute on passengers if entity @s[tag=aj.human1.bone.right_leg] run function animated_java:human1/variants/sally_damaged/zzz/5
execute on passengers if entity @s[tag=aj.human1.bone.left_leg] run function animated_java:human1/variants/sally_damaged/zzz/6
execute on passengers if entity @s[tag=aj.human1.bone.body] run function animated_java:human1/variants/sally_damaged/zzz/7