# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:garapapas/root/zzz/1 with entity @s data.locators.right_leg
function animated_java:garapapas/root/zzz/3 with entity @s data.locators.left_leg
function animated_java:garapapas/root/zzz/5 with entity @s data.locators.tail2
function animated_java:garapapas/root/zzz/7 with entity @s data.locators.tail1
function animated_java:garapapas/root/zzz/9 with entity @s data.locators.neck
function animated_java:garapapas/root/zzz/11 with entity @s data.locators.head
function animated_java:garapapas/root/zzz/13 with entity @s data.locators.front_body
function animated_java:garapapas/root/zzz/15 with entity @s data.locators.right_arm
function animated_java:garapapas/root/zzz/17 with entity @s data.locators.left_arm