# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.garuda.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'garuda', 'function_path': 'animated_java:garuda/variants/default_shaking/apply'}
execute on passengers if entity @s[tag=aj.garuda.bone.left_leg4] run function animated_java:garuda/variants/default_shaking/zzz/0
execute on passengers if entity @s[tag=aj.garuda.bone.left_leg3] run function animated_java:garuda/variants/default_shaking/zzz/1
execute on passengers if entity @s[tag=aj.garuda.bone.left_leg2] run function animated_java:garuda/variants/default_shaking/zzz/2
execute on passengers if entity @s[tag=aj.garuda.bone.left_leg1] run function animated_java:garuda/variants/default_shaking/zzz/3
execute on passengers if entity @s[tag=aj.garuda.bone.right_leg4] run function animated_java:garuda/variants/default_shaking/zzz/4
execute on passengers if entity @s[tag=aj.garuda.bone.right_leg3] run function animated_java:garuda/variants/default_shaking/zzz/5
execute on passengers if entity @s[tag=aj.garuda.bone.right_leg2] run function animated_java:garuda/variants/default_shaking/zzz/6
execute on passengers if entity @s[tag=aj.garuda.bone.right_leg1] run function animated_java:garuda/variants/default_shaking/zzz/7
execute on passengers if entity @s[tag=aj.garuda.bone.right_wing3] run function animated_java:garuda/variants/default_shaking/zzz/8
execute on passengers if entity @s[tag=aj.garuda.bone.right_wing2] run function animated_java:garuda/variants/default_shaking/zzz/9
execute on passengers if entity @s[tag=aj.garuda.bone.right_wing1] run function animated_java:garuda/variants/default_shaking/zzz/10
execute on passengers if entity @s[tag=aj.garuda.bone.left_wing3] run function animated_java:garuda/variants/default_shaking/zzz/11
execute on passengers if entity @s[tag=aj.garuda.bone.left_wing2] run function animated_java:garuda/variants/default_shaking/zzz/12
execute on passengers if entity @s[tag=aj.garuda.bone.left_wing1] run function animated_java:garuda/variants/default_shaking/zzz/13
execute on passengers if entity @s[tag=aj.garuda.bone.beak_down] run function animated_java:garuda/variants/default_shaking/zzz/14
execute on passengers if entity @s[tag=aj.garuda.bone.beak_up] run function animated_java:garuda/variants/default_shaking/zzz/15
execute on passengers if entity @s[tag=aj.garuda.bone.head1] run function animated_java:garuda/variants/default_shaking/zzz/16
execute on passengers if entity @s[tag=aj.garuda.bone.neck2] run function animated_java:garuda/variants/default_shaking/zzz/17
execute on passengers if entity @s[tag=aj.garuda.bone.neck1] run function animated_java:garuda/variants/default_shaking/zzz/18
execute on passengers if entity @s[tag=aj.garuda.bone.body3] run function animated_java:garuda/variants/default_shaking/zzz/19
execute on passengers if entity @s[tag=aj.garuda.bone.body2] run function animated_java:garuda/variants/default_shaking/zzz/20
execute on passengers if entity @s[tag=aj.garuda.bone.tail2] run function animated_java:garuda/variants/default_shaking/zzz/21
execute on passengers if entity @s[tag=aj.garuda.bone.tail1] run function animated_java:garuda/variants/default_shaking/zzz/22
execute on passengers if entity @s[tag=aj.garuda.bone.body1] run function animated_java:garuda/variants/default_shaking/zzz/23