# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.squirrel.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'squirrel', 'function_path': 'animated_java:squirrel/animations/pause_all'}
tag @s remove aj.squirrel.animation.default.playing
tag @s remove aj.squirrel.animation.die.playing
tag @s remove aj.squirrel.animation.bite.playing
tag @s remove aj.squirrel.animation.spin_left.playing
tag @s remove aj.squirrel.animation.walk.playing
tag @s remove aj.squirrel.animation.bark.playing