# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.default.frame dummy
scoreboard objectives add aj.die.frame dummy
scoreboard objectives add aj.bite.frame dummy
scoreboard objectives add aj.spin_left.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.bark.frame dummy
scoreboard objectives add aj.spin_right.frame dummy