# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ojinushi.root] run return 0
function #animated_java:ojinushi/as_root/pre_tick
execute if entity @s[tag=aj.ojinushi.animation.default.playing] run function animated_java:ojinushi/animations/default/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.die.playing] run function animated_java:ojinushi/animations/die/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.right_punch.playing] run function animated_java:ojinushi/animations/right_punch/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.launch.playing] run function animated_java:ojinushi/animations/launch/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.bark.playing] run function animated_java:ojinushi/animations/bark/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.jump_launch1.playing] run function animated_java:ojinushi/animations/jump_launch1/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.jump_launch2.playing] run function animated_java:ojinushi/animations/jump_launch2/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.jump_launch2_right2.playing] run function animated_java:ojinushi/animations/jump_launch2_right2/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.jump_launch2_right.playing] run function animated_java:ojinushi/animations/jump_launch2_right/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.bite.playing] run function animated_java:ojinushi/animations/bite/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.bite_left.playing] run function animated_java:ojinushi/animations/bite_left/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.bite_right.playing] run function animated_java:ojinushi/animations/bite_right/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.walk.playing] run function animated_java:ojinushi/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.tired.playing] run function animated_java:ojinushi/animations/tired/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.right_punch1.playing] run function animated_java:ojinushi/animations/right_punch1/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.right_punch2.playing] run function animated_java:ojinushi/animations/right_punch2/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.bite_right1.playing] run function animated_java:ojinushi/animations/bite_right1/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.bite_right2.playing] run function animated_java:ojinushi/animations/bite_right2/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.bite_left1.playing] run function animated_java:ojinushi/animations/bite_left1/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.bite_left2.playing] run function animated_java:ojinushi/animations/bite_left2/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.launch1.playing] run function animated_java:ojinushi/animations/launch1/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.launch2.playing] run function animated_java:ojinushi/animations/launch2/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.sidestep_left.playing] run function animated_java:ojinushi/animations/sidestep_left/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.launch_up.playing] run function animated_java:ojinushi/animations/launch_up/zzz/on_tick
execute if entity @s[tag=aj.ojinushi.animation.sidestep_right.playing] run function animated_java:ojinushi/animations/sidestep_right/zzz/on_tick
execute on passengers if entity @s[tag=aj.ojinushi.data] run function animated_java:ojinushi/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
execute on vehicle run function anemoland_contents:sys/entity/mob/ojinushi/tick/0
function #animated_java:ojinushi/as_root/post_tick