# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.squirrel.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'squirrel', 'function_path': 'animated_java:squirrel/variants/damaged/apply'}
execute on passengers if entity @s[tag=aj.squirrel.bone.right_leg] run function animated_java:squirrel/variants/damaged/zzz/0
execute on passengers if entity @s[tag=aj.squirrel.bone.left_leg] run function animated_java:squirrel/variants/damaged/zzz/1
execute on passengers if entity @s[tag=aj.squirrel.bone.tail] run function animated_java:squirrel/variants/damaged/zzz/2
execute on passengers if entity @s[tag=aj.squirrel.bone.jaw] run function animated_java:squirrel/variants/damaged/zzz/3
execute on passengers if entity @s[tag=aj.squirrel.bone.head] run function animated_java:squirrel/variants/damaged/zzz/4
execute on passengers if entity @s[tag=aj.squirrel.bone.neck1] run function animated_java:squirrel/variants/damaged/zzz/5
execute on passengers if entity @s[tag=aj.squirrel.bone.front_body] run function animated_java:squirrel/variants/damaged/zzz/6
execute on passengers if entity @s[tag=aj.squirrel.bone.back_body] run function animated_java:squirrel/variants/damaged/zzz/7