# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.garuda.root] run return 0
function #animated_java:garuda/as_root/pre_tick
execute if entity @s[tag=aj.garuda.animation.default.playing] run function animated_java:garuda/animations/default/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.die.playing] run function animated_java:garuda/animations/die/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.walk.playing] run function animated_java:garuda/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.bark.playing] run function animated_java:garuda/animations/bark/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.pick1_jump.playing] run function animated_java:garuda/animations/pick1_jump/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.pick2.playing] run function animated_java:garuda/animations/pick2/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.wing_left1.playing] run function animated_java:garuda/animations/wing_left1/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.wing_left2.playing] run function animated_java:garuda/animations/wing_left2/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.pick1.playing] run function animated_java:garuda/animations/pick1/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.jump1.playing] run function animated_java:garuda/animations/jump1/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.jump2.playing] run function animated_java:garuda/animations/jump2/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.jump3.playing] run function animated_java:garuda/animations/jump3/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.tired.playing] run function animated_java:garuda/animations/tired/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.dash1.playing] run function animated_java:garuda/animations/dash1/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.dash2.playing] run function animated_java:garuda/animations/dash2/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.dash3.playing] run function animated_java:garuda/animations/dash3/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.fly_keep.playing] run function animated_java:garuda/animations/fly_keep/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.summer_salt_right1.playing] run function animated_java:garuda/animations/summer_salt_right1/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.summer_salt_right2.playing] run function animated_java:garuda/animations/summer_salt_right2/zzz/on_tick
execute if entity @s[tag=aj.garuda.animation.summer_salt_right1_copy.playing] run function animated_java:garuda/animations/summer_salt_right1_copy/zzz/on_tick
execute on passengers if entity @s[tag=aj.garuda.data] run function animated_java:garuda/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
execute on vehicle run function anemoland_contents:sys/entity/mob/garuda/tick/0
function #animated_java:garuda/as_root/post_tick