# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.squirrel_head.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'squirrel_head', 'function_path': 'animated_java:squirrel_head/animations/pause_all'}
tag @s remove aj.squirrel_head.animation.default.playing
tag @s remove aj.squirrel_head.animation.die.playing
tag @s remove aj.squirrel_head.animation.bite1.playing
tag @s remove aj.squirrel_head.animation.bite2.playing
tag @s remove aj.squirrel_head.animation.spin_left1.playing
tag @s remove aj.squirrel_head.animation.spin_left2.playing
tag @s remove aj.squirrel_head.animation.spin_right1.playing
tag @s remove aj.squirrel_head.animation.spin_right2.playing
tag @s remove aj.squirrel_head.animation.walk.playing
tag @s remove aj.squirrel_head.animation.bite_left1.playing
tag @s remove aj.squirrel_head.animation.bite_left2.playing
tag @s remove aj.squirrel_head.animation.bite_right1.playing
tag @s remove aj.squirrel_head.animation.bite_right2.playing
tag @s remove aj.squirrel_head.animation.tackle_left1.playing
tag @s remove aj.squirrel_head.animation.tackle_left2.playing
tag @s remove aj.squirrel_head.animation.tackle_right1.playing
tag @s remove aj.squirrel_head.animation.tackle_right2.playing
tag @s remove aj.squirrel_head.animation.bark.playing
tag @s remove aj.squirrel_head.animation.tired.playing
tag @s remove aj.squirrel_head.animation.spin_tail_left1.playing
tag @s remove aj.squirrel_head.animation.spin_jump_left1.playing
tag @s remove aj.squirrel_head.animation.spin_jump_left2.playing
tag @s remove aj.squirrel_head.animation.spin_jump3.playing