# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.bagikeros.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'bagikeros', 'function_path': 'animated_java:bagikeros/variants/damaged/apply'}
execute on passengers if entity @s[tag=aj.bagikeros.bone.jaw] run function animated_java:bagikeros/variants/damaged/zzz/0
execute on passengers if entity @s[tag=aj.bagikeros.bone.head] run function animated_java:bagikeros/variants/damaged/zzz/1
execute on passengers if entity @s[tag=aj.bagikeros.bone.neck] run function animated_java:bagikeros/variants/damaged/zzz/2
execute on passengers if entity @s[tag=aj.bagikeros.bone.left_arm3] run function animated_java:bagikeros/variants/damaged/zzz/3
execute on passengers if entity @s[tag=aj.bagikeros.bone.left_arm2] run function animated_java:bagikeros/variants/damaged/zzz/4
execute on passengers if entity @s[tag=aj.bagikeros.bone.left_arm1] run function animated_java:bagikeros/variants/damaged/zzz/5
execute on passengers if entity @s[tag=aj.bagikeros.bone.right_arm3] run function animated_java:bagikeros/variants/damaged/zzz/6
execute on passengers if entity @s[tag=aj.bagikeros.bone.right_arm2] run function animated_java:bagikeros/variants/damaged/zzz/7
execute on passengers if entity @s[tag=aj.bagikeros.bone.right_arm1] run function animated_java:bagikeros/variants/damaged/zzz/8
execute on passengers if entity @s[tag=aj.bagikeros.bone.body2] run function animated_java:bagikeros/variants/damaged/zzz/9
execute on passengers if entity @s[tag=aj.bagikeros.bone.left_leg3] run function animated_java:bagikeros/variants/damaged/zzz/10
execute on passengers if entity @s[tag=aj.bagikeros.bone.left_leg2] run function animated_java:bagikeros/variants/damaged/zzz/11
execute on passengers if entity @s[tag=aj.bagikeros.bone.left_leg1] run function animated_java:bagikeros/variants/damaged/zzz/12
execute on passengers if entity @s[tag=aj.bagikeros.bone.right_leg3] run function animated_java:bagikeros/variants/damaged/zzz/13
execute on passengers if entity @s[tag=aj.bagikeros.bone.right_leg2] run function animated_java:bagikeros/variants/damaged/zzz/14
execute on passengers if entity @s[tag=aj.bagikeros.bone.right_leg1] run function animated_java:bagikeros/variants/damaged/zzz/15
execute on passengers if entity @s[tag=aj.bagikeros.bone.tail3_up] run function animated_java:bagikeros/variants/damaged/zzz/16
execute on passengers if entity @s[tag=aj.bagikeros.bone.tail3_down] run function animated_java:bagikeros/variants/damaged/zzz/17
execute on passengers if entity @s[tag=aj.bagikeros.bone.tail2] run function animated_java:bagikeros/variants/damaged/zzz/18
execute on passengers if entity @s[tag=aj.bagikeros.bone.tail1] run function animated_java:bagikeros/variants/damaged/zzz/19
execute on passengers if entity @s[tag=aj.bagikeros.bone.body1] run function animated_java:bagikeros/variants/damaged/zzz/20