# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mushroom_fang.root] run return 0
function #animated_java:mushroom_fang/as_root/pre_tick
execute if entity @s[tag=aj.mushroom_fang.animation.default.playing] run function animated_java:mushroom_fang/animations/default/zzz/on_tick
execute if entity @s[tag=aj.mushroom_fang.animation.fast.playing] run function animated_java:mushroom_fang/animations/fast/zzz/on_tick
execute on passengers if entity @s[tag=aj.mushroom_fang.data] run function animated_java:mushroom_fang/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
function #animated_java:mushroom_fang/as_root/post_tick