# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle explosion ~ ~0.3 ~ 0 0 0 0 1
execute as @a[distance=..64] at @s run playsound entity.generic.explode hostile @s ~ ~ ~ 0.5 0
function anemoland_contents:sys/entity/bullet/mushroom_fang/attack/default/0