# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.human1.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'human1', 'function_path': 'animated_java:human1/animations/standing3/apply_frame'}
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.standing3.frame $(frame)
execute at @s run function animated_java:human1/animations/standing3/zzz/apply_frame with storage aj:temp