# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.bagikeros.locator', 'aj.bagikeros.locator.head']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:bagikeros/zzz/2
data modify entity @s data.locators.head.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.bagikeros.locator', 'aj.bagikeros.locator.left_arm']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:bagikeros/zzz/3
data modify entity @s data.locators.left_arm.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.bagikeros.locator', 'aj.bagikeros.locator.right_arm']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:bagikeros/zzz/4
data modify entity @s data.locators.right_arm.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.bagikeros.locator', 'aj.bagikeros.locator.front_body']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:bagikeros/zzz/5
data modify entity @s data.locators.front_body.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.bagikeros.locator', 'aj.bagikeros.locator.left_leg']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:bagikeros/zzz/6
data modify entity @s data.locators.left_leg.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.bagikeros.locator', 'aj.bagikeros.locator.right_leg']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:bagikeros/zzz/7
data modify entity @s data.locators.right_leg.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.bagikeros.locator', 'aj.bagikeros.locator.tail2']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:bagikeros/zzz/8
data modify entity @s data.locators.tail2.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.bagikeros.locator', 'aj.bagikeros.locator.tail1']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:bagikeros/zzz/9
data modify entity @s data.locators.tail1.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.jaw] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_jaw set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.neck] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.left_arm3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.left_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.left_arm1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.right_arm3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.right_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.right_arm1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.body2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.left_leg3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.left_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.left_leg1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.right_leg3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.right_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.right_leg1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.tail3_up] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail3_up set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.tail3_down] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail3_down set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.tail2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.tail1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bagikeros.bone.body1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body1 set from storage aj:uuid main.out