# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.head.uuid
function animated_java:bagikeros/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.left_arm.uuid
function animated_java:bagikeros/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.right_arm.uuid
function animated_java:bagikeros/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.front_body.uuid
function animated_java:bagikeros/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.left_leg.uuid
function animated_java:bagikeros/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.right_leg.uuid
function animated_java:bagikeros/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.tail2.uuid
function animated_java:bagikeros/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.tail1.uuid
function animated_java:bagikeros/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator.uuid
function animated_java:bagikeros/zzz/execute with storage aj:temp