# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.carnara.root] run return 0
function #animated_java:carnara/as_root/pre_tick
execute if entity @s[tag=aj.carnara.animation.default.playing] run function animated_java:carnara/animations/default/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.die.playing] run function animated_java:carnara/animations/die/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.dive1.playing] run function animated_java:carnara/animations/dive1/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.dive2.playing] run function animated_java:carnara/animations/dive2/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam1.playing] run function animated_java:carnara/animations/beam1/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.to_underground_copy1.playing] run function animated_java:carnara/animations/to_underground_copy1/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.to_underground_copy2.playing] run function animated_java:carnara/animations/to_underground_copy2/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.to_underground_copy3.playing] run function animated_java:carnara/animations/to_underground_copy3/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.to_underground_copy4.playing] run function animated_java:carnara/animations/to_underground_copy4/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.to_underground.playing] run function animated_java:carnara/animations/to_underground/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.underground_jump.playing] run function animated_java:carnara/animations/underground_jump/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam2.playing] run function animated_java:carnara/animations/beam2/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.drag_head_left1.playing] run function animated_java:carnara/animations/drag_head_left1/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.drag_head_left2.playing] run function animated_java:carnara/animations/drag_head_left2/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.drag_head_right1.playing] run function animated_java:carnara/animations/drag_head_right1/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.drag_head_right2.playing] run function animated_java:carnara/animations/drag_head_right2/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.tail_spear_left1.playing] run function animated_java:carnara/animations/tail_spear_left1/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.tail_spear_left2.playing] run function animated_java:carnara/animations/tail_spear_left2/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.tail_spear_right1.playing] run function animated_java:carnara/animations/tail_spear_right1/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.tail_spear_right2.playing] run function animated_java:carnara/animations/tail_spear_right2/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam2_left.playing] run function animated_java:carnara/animations/beam2_left/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam2_right.playing] run function animated_java:carnara/animations/beam2_right/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.drag_tail_left1.playing] run function animated_java:carnara/animations/drag_tail_left1/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.drag_tail_left2.playing] run function animated_java:carnara/animations/drag_tail_left2/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.drag_tail_right1.playing] run function animated_java:carnara/animations/drag_tail_right1/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.drag_tail_right2.playing] run function animated_java:carnara/animations/drag_tail_right2/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.bark.playing] run function animated_java:carnara/animations/bark/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam_high_left1.playing] run function animated_java:carnara/animations/beam_high_left1/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam_high_left2.playing] run function animated_java:carnara/animations/beam_high_left2/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam_high_right1.playing] run function animated_java:carnara/animations/beam_high_right1/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam_high_right2.playing] run function animated_java:carnara/animations/beam_high_right2/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam_high_left2_far.playing] run function animated_java:carnara/animations/beam_high_left2_far/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam_high_right2_far.playing] run function animated_java:carnara/animations/beam_high_right2_far/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam_high_turn_left1.playing] run function animated_java:carnara/animations/beam_high_turn_left1/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam_high_turn_right1.playing] run function animated_java:carnara/animations/beam_high_turn_right1/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.turn_left.playing] run function animated_java:carnara/animations/turn_left/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.turn_right.playing] run function animated_java:carnara/animations/turn_right/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam_turn_left.playing] run function animated_java:carnara/animations/beam_turn_left/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.beam_turn_right.playing] run function animated_java:carnara/animations/beam_turn_right/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.walk.playing] run function animated_java:carnara/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.walk_copy.playing] run function animated_java:carnara/animations/walk_copy/zzz/on_tick
execute if entity @s[tag=aj.carnara.animation.tired.playing] run function animated_java:carnara/animations/tired/zzz/on_tick
execute on passengers if entity @s[tag=aj.carnara.data] run function animated_java:carnara/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
execute on vehicle run function anemoland_contents:sys/entity/mob/carnara/tick/0
function #animated_java:carnara/as_root/post_tick