# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.garapas.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'garapas', 'function_path': 'animated_java:garapas/variants/default/apply'}
execute on passengers if entity @s[tag=aj.garapas.bone.left_leg3] run function animated_java:garapas/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.garapas.bone.left_leg2] run function animated_java:garapas/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.garapas.bone.left_leg1] run function animated_java:garapas/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.garapas.bone.right_leg3] run function animated_java:garapas/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.garapas.bone.right_leg2] run function animated_java:garapas/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.garapas.bone.right_leg1] run function animated_java:garapas/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.garapas.bone.tail] run function animated_java:garapas/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.garapas.bone.beak_up] run function animated_java:garapas/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.garapas.bone.beak_down] run function animated_java:garapas/variants/default/zzz/8
execute on passengers if entity @s[tag=aj.garapas.bone.head] run function animated_java:garapas/variants/default/zzz/9
execute on passengers if entity @s[tag=aj.garapas.bone.neck2] run function animated_java:garapas/variants/default/zzz/10
execute on passengers if entity @s[tag=aj.garapas.bone.right_arm3] run function animated_java:garapas/variants/default/zzz/11
execute on passengers if entity @s[tag=aj.garapas.bone.right_arm2] run function animated_java:garapas/variants/default/zzz/12
execute on passengers if entity @s[tag=aj.garapas.bone.right_arm1] run function animated_java:garapas/variants/default/zzz/13
execute on passengers if entity @s[tag=aj.garapas.bone.left_arm3] run function animated_java:garapas/variants/default/zzz/14
execute on passengers if entity @s[tag=aj.garapas.bone.left_arm2] run function animated_java:garapas/variants/default/zzz/15
execute on passengers if entity @s[tag=aj.garapas.bone.left_arm1] run function animated_java:garapas/variants/default/zzz/16
execute on passengers if entity @s[tag=aj.garapas.bone.body] run function animated_java:garapas/variants/default/zzz/17