# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.human1.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'human1', 'function_path': 'animated_java:human1/animations/pause_all'}
tag @s remove aj.human1.animation.default.playing
tag @s remove aj.human1.animation.walk.playing
tag @s remove aj.human1.animation.attack.playing
tag @s remove aj.human1.animation.thinking.playing
tag @s remove aj.human1.animation.standing1.playing
tag @s remove aj.human1.animation.keep_distance1.playing
tag @s remove aj.human1.animation.keep_distance_copy2.playing
tag @s remove aj.human1.animation.attack_copy2.playing
tag @s remove aj.human1.animation.attack_copy3.playing
tag @s remove aj.human1.animation.attack1.playing
tag @s remove aj.human1.animation.waiting1.playing
tag @s remove aj.human1.animation.waiting_copy2.playing
tag @s remove aj.human1.animation.standing2.playing