# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.right_arm.uuid
function animated_java:ojinushi/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.head.uuid
function animated_java:ojinushi/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.left_arm.uuid
function animated_java:ojinushi/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator.uuid
function animated_java:ojinushi/zzz/execute with storage aj:temp