# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:squirrel_head/root/zzz/1 with entity @s data.locators.hitbox_tail1
function animated_java:squirrel_head/root/zzz/3 with entity @s data.locators.hitbox_tail2
function animated_java:squirrel_head/root/zzz/5 with entity @s data.locators.hitbox_neck
function animated_java:squirrel_head/root/zzz/7 with entity @s data.locators.hitbox_head