# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:squirrel/remove/zzz/kill with entity @s data.locators.tail
function animated_java:squirrel/remove/zzz/kill with entity @s data.locators.head