# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:spider/animations/jump_charge/zzz/apply_frame {frame: 12}
scoreboard players add @s aj.jump_charge.frame 1