# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.bagikeros.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'bagikeros', 'function_path': 'animated_java:bagikeros/animations/pause_all'}
tag @s remove aj.bagikeros.animation.default.playing
tag @s remove aj.bagikeros.animation.die.playing
tag @s remove aj.bagikeros.animation.bite1.playing
tag @s remove aj.bagikeros.animation.bite2.playing
tag @s remove aj.bagikeros.animation.bark.playing
tag @s remove aj.bagikeros.animation.dive1.playing
tag @s remove aj.bagikeros.animation.dive2.playing
tag @s remove aj.bagikeros.animation.shake_head1.playing
tag @s remove aj.bagikeros.animation.shake_head2.playing
tag @s remove aj.bagikeros.animation.walk.playing
tag @s remove aj.bagikeros.animation.shake_walk.playing
tag @s remove aj.bagikeros.animation.shake_tail1.playing
tag @s remove aj.bagikeros.animation.shake_tail2.playing
tag @s remove aj.bagikeros.animation.shake_walk_end.playing
tag @s remove aj.bagikeros.animation.shake_walk_start.playing
tag @s remove aj.bagikeros.animation.bite_left1.playing
tag @s remove aj.bagikeros.animation.bite_left2.playing
tag @s remove aj.bagikeros.animation.bite_right1.playing
tag @s remove aj.bagikeros.animation.bite_right2.playing
tag @s remove aj.bagikeros.animation.tired.playing
tag @s remove aj.bagikeros.animation.fire_head.playing