# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.muscleroom.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'muscleroom', 'function_path': 'animated_java:muscleroom/animations/pause_all'}
tag @s remove aj.muscleroom.animation.default.playing
tag @s remove aj.muscleroom.animation.walk.playing
tag @s remove aj.muscleroom.animation.jump.playing
tag @s remove aj.muscleroom.animation.ground.playing
tag @s remove aj.muscleroom.animation.bark.playing
tag @s remove aj.muscleroom.animation.die.playing
tag @s remove aj.muscleroom.animation.left_punch.playing
tag @s remove aj.muscleroom.animation.ground1.playing
tag @s remove aj.muscleroom.animation.ground2.playing
tag @s remove aj.muscleroom.animation.backstep.playing
tag @s remove aj.muscleroom.animation.left_punch1.playing
tag @s remove aj.muscleroom.animation.left_punch2.playing
tag @s remove aj.muscleroom.animation.tired.playing