# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:bagikeros/remove/zzz/kill with entity @s data.locators.hitbox_head
function animated_java:bagikeros/remove/zzz/kill with entity @s data.locators.hitbox_left_arm
function animated_java:bagikeros/remove/zzz/kill with entity @s data.locators.hitbox_right_arm
function animated_java:bagikeros/remove/zzz/kill with entity @s data.locators.hitbox_front_body
function animated_java:bagikeros/remove/zzz/kill with entity @s data.locators.hitbox_left_leg
function animated_java:bagikeros/remove/zzz/kill with entity @s data.locators.hitbox_right_leg
function animated_java:bagikeros/remove/zzz/kill with entity @s data.locators.hitbox_tail2
function animated_java:bagikeros/remove/zzz/kill with entity @s data.locators.hitbox_tail1