# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_leg4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_leg3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_leg1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_leg4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_leg3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_leg1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_wing3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_wing3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_wing2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_wing2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.right_wing1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_wing1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_wing3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_wing3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_wing2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_wing2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.left_wing1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_wing1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.beak_down] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_beak_down set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.beak_up] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_beak_up set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.neck2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.neck1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.body3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.body2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.tail2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.tail1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.garuda.node.body1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body1 set from storage aj:uuid main.out