# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.spider.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'spider', 'function_path': 'animated_java:spider/animations/pause_all'}
tag @s remove aj.spider.animation.default.playing
tag @s remove aj.spider.animation.die.playing
tag @s remove aj.spider.animation.walk.playing
tag @s remove aj.spider.animation.jump_charge.playing
tag @s remove aj.spider.animation.jump.playing
tag @s remove aj.spider.animation.jump_end.playing