# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.martellos.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'martellos', 'function_path': 'animated_java:martellos/variants/amethyst/apply'}
execute on passengers if entity @s[tag=aj.martellos.bone.jaw] run function animated_java:martellos/variants/amethyst/zzz/0
execute on passengers if entity @s[tag=aj.martellos.bone.head] run function animated_java:martellos/variants/amethyst/zzz/1
execute on passengers if entity @s[tag=aj.martellos.bone.neck] run function animated_java:martellos/variants/amethyst/zzz/2
execute on passengers if entity @s[tag=aj.martellos.bone.right_arm2] run function animated_java:martellos/variants/amethyst/zzz/3
execute on passengers if entity @s[tag=aj.martellos.bone.right_arm1] run function animated_java:martellos/variants/amethyst/zzz/4
execute on passengers if entity @s[tag=aj.martellos.bone.left_arm2] run function animated_java:martellos/variants/amethyst/zzz/5
execute on passengers if entity @s[tag=aj.martellos.bone.left_arm1] run function animated_java:martellos/variants/amethyst/zzz/6
execute on passengers if entity @s[tag=aj.martellos.bone.body2] run function animated_java:martellos/variants/amethyst/zzz/7
execute on passengers if entity @s[tag=aj.martellos.bone.right_leg2] run function animated_java:martellos/variants/amethyst/zzz/8
execute on passengers if entity @s[tag=aj.martellos.bone.right_leg1] run function animated_java:martellos/variants/amethyst/zzz/9
execute on passengers if entity @s[tag=aj.martellos.bone.left_leg2] run function animated_java:martellos/variants/amethyst/zzz/10
execute on passengers if entity @s[tag=aj.martellos.bone.left_leg1] run function animated_java:martellos/variants/amethyst/zzz/11
execute on passengers if entity @s[tag=aj.martellos.bone.tail3] run function animated_java:martellos/variants/amethyst/zzz/12
execute on passengers if entity @s[tag=aj.martellos.bone.tail2] run function animated_java:martellos/variants/amethyst/zzz/13
execute on passengers if entity @s[tag=aj.martellos.bone.tail1] run function animated_java:martellos/variants/amethyst/zzz/14
execute on passengers if entity @s[tag=aj.martellos.bone.body1] run function animated_java:martellos/variants/amethyst/zzz/15